#!/bin/bash

# Guide pour créer les tables via le Dashboard Railway

GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

clear

echo -e "${BLUE}"
echo "╔════════════════════════════════════════════════════════╗"
echo "║                                                        ║"
echo "║  🗄️  CRÉER LES TABLES - VIA RAILWAY DASHBOARD        ║"
echo "║                                                        ║"
echo "╚════════════════════════════════════════════════════════╝"
echo -e "${NC}"
echo ""

echo -e "${YELLOW}📋 ÉTAPES À SUIVRE :${NC}"
echo ""
echo "1. Le dashboard Railway va s'ouvrir dans votre navigateur"
echo ""
echo "2. Cliquez sur votre service ${GREEN}backend${NC} (pas PostgreSQL)"
echo ""
echo "3. Allez dans l'onglet ${GREEN}'Deployments'${NC}"
echo ""
echo "4. Cliquez sur le ${GREEN}dernier déploiement${NC} (celui tout en haut)"
echo ""
echo "5. En haut à droite, cherchez l'icône ${GREEN}🖥️ 'Shell'${NC} et cliquez dessus"
echo ""
echo "6. Un terminal s'ouvrira. Copiez-collez ces commandes ${GREEN}UNE PAR UNE${NC} :"
echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${BLUE}# Première commande - Créer les tables :${NC}"
echo -e "${GREEN}npx prisma migrate deploy${NC}"
echo ""
echo -e "${YELLOW}   ⏳ Attendez que ça se termine (environ 10 secondes)${NC}"
echo -e "${YELLOW}   ✅ Vous verrez : 'Migration applied successfully'${NC}"
echo ""
echo -e "${BLUE}# Deuxième commande - Insérer les données initiales :${NC}"
echo -e "${GREEN}npx prisma db seed${NC}"
echo ""
echo -e "${YELLOW}   ⏳ Attendez que ça se termine (environ 5 secondes)${NC}"
echo -e "${YELLOW}   ✅ Vous verrez : 'Database seeded successfully'${NC}"
echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${BLUE}7. C'est terminé ! Fermez le Shell${NC}"
echo ""
echo ""
echo -e "${YELLOW}💡 ASTUCE :${NC}"
echo "Si le Shell ne s'ouvre pas, essayez depuis l'onglet 'Settings' → 'Service' → Actions → 'Open Shell'"
echo ""
echo ""

read -p "Appuyez sur Entrée pour ouvrir le dashboard Railway..."

railway open

echo ""
echo ""
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${YELLOW}📝 RÉSUMÉ DES COMMANDES À TAPER :${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "1. npx prisma migrate deploy"
echo "2. npx prisma db seed"
echo ""
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

echo ""
read -p "✓ Tables créées et données insérées ? (Entrée pour continuer)"

echo ""
echo -e "${GREEN}"
echo "╔════════════════════════════════════════════════════════╗"
echo "║                                                        ║"
echo "║     ✅ BASE DE DONNÉES PRÊTE !                        ║"
echo "║                                                        ║"
echo "╚════════════════════════════════════════════════════════╝"
echo -e "${NC}"
echo ""

echo -e "${BLUE}📊 Ce qui a été créé :${NC}"
echo ""
echo "📦 Tables :"
echo "  • users, roles, permissions"
echo "  • user_roles, role_permissions"
echo "  • user_xp, badges, user_badges"
echo "  • courses, lessons, course_progress"
echo "  • quizzes, quiz_questions, quiz_results"
echo "  • activity_logs, discord_notifications"
echo "  • projects"
echo ""
echo "🌱 Données initiales :"
echo "  • 5 rôles (admin, moderator, user, dev_pro, gaming_pro)"
echo "  • Permissions RBAC complètes"
echo "  • 12+ badges système"
echo "  • 3 cours de démonstration"
echo ""
echo -e "${GREEN}🎉 Votre backend est maintenant complètement opérationnel !${NC}"
echo ""
